import { NextResponse } from "next/server";

export async function GET() {
  const mockData = [
    {
      id: "1",
      employeeId: "#U1323",
      name: "David Do",
      avatar: "/avatars/david.jpg",
      email: "capiproduct@gmail.com",
      phone: "0984274274",
      role: "HR Manager",
      reimbursement: 9500000,
      status: "On-Time" as const,
    },
    {
      id: "2",
      employeeId: "#U1324",
      name: "Sarah Wilson",
      avatar: "/avatars/sarah.jpg",
      email: "ducphu.forwork@gmail.com",
      phone: "0984274275",
      role: "Developer",
      reimbursement: 9500000,
      status: "Sick Leave" as const,
    },
    {
      id: "3",
      employeeId: "#U1325",
      name: "John Smith",
      avatar: "/avatars/john.jpg",
      email: "example@gmail.co",
      phone: "0984274276",
      role: "UI/UX Designer",
      reimbursement: 9500000,
      status: "Late" as const,
    },
    {
      id: "4",
      employeeId: "#U1326",
      name: "Emma Brown",
      avatar: "/avatars/emma.jpg",
      email: "example@gmail.co",
      phone: "0984274277",
      role: "Account Manager",
      reimbursement: 9500000,
      status: "On-Time" as const,
    },
    {
      id: "5",
      employeeId: "#U1323",
      name: "David Do",
      avatar: "/avatars/david.jpg",
      email: "capiproduct@gmail.com",
      phone: "0984274274",
      role: "HR Manager",
      reimbursement: 9500000,
      status: "On-Time" as const,
    },
    {
      id: "6",
      employeeId: "#U1324",
      name: "Sarah Wilson",
      avatar: "/avatars/sarah.jpg",
      email: "ducphu.forwork@gmail.com",
      phone: "0984274275",
      role: "Developer",
      reimbursement: 9500000,
      status: "Sick Leave" as const,
    },
    {
      id: "7",
      employeeId: "#U1325",
      name: "John Smith",
      avatar: "/avatars/john.jpg",
      email: "example@gmail.co",
      phone: "0984274276",
      role: "UI/UX Designer",
      reimbursement: 9500000,
      status: "Late" as const,
    },
    {
      id: "8",
      employeeId: "#U1326",
      name: "Emma Brown",
      avatar: "/avatars/emma.jpg",
      email: "example@gmail.co",
      phone: "0984274277",
      role: "Account Manager",
      reimbursement: 9500000,
      status: "On-Time" as const,
    },
    {
      id: "9",
      employeeId: "#U1324",
      name: "Sarah Wilson",
      avatar: "/avatars/sarah.jpg",
      email: "ducphu.forwork@gmail.com",
      phone: "0984274275",
      role: "Developer",
      reimbursement: 9500000,
      status: "Sick Leave" as const,
    },
    {
      id: "10",
      employeeId: "#U1325",
      name: "John Smith",
      avatar: "/avatars/john.jpg",
      email: "example@gmail.co",
      phone: "0984274276",
      role: "UI/UX Designer",
      reimbursement: 9500000,
      status: "Late" as const,
    },
    {
      id: "11",
      employeeId: "#U1326",
      name: "Emma Brown",
      avatar: "/avatars/emma.jpg",
      email: "example@gmail.co",
      phone: "0984274277",
      role: "Account Manager",
      reimbursement: 9500000,
      status: "On-Time" as const,
    },
  ];

  return NextResponse.json(mockData);
}
